create table
    public.todos (
                     id bigint generated by default as identity not null,
                     user_id uuid not null,
                     task text not null,
                     is_complete boolean not null default false,
                     inserted_at timestamp with time zone not null default timezone ('utc'::text, now()),
                     deleted_at date null,
                     completed_at date null,
                     "order" real not null,
                     constraint todos_pkey primary key (id),
                     constraint todos_user_id_fkey foreign key (user_id) references auth.users (id),
                     constraint todos_task_check check ((char_length(task) > 3))
) tablespace pg_default;